set(FUSIONDESK_TOOLCHAIN_ENV_PREFIX FUSIONDESK_LINUX_RK3588)
set(FUSIONDESK_TOOLCHAIN_PROCESSOR aarch64)
set(FUSIONDESK_TARGET_SOC rk3588 CACHE STRING "FusionDesk target SoC")
include("${CMAKE_CURRENT_LIST_DIR}/linux-cross-common.cmake")
